### ISSUE TITLE
insertAtBegin method is not working in double linked list in your solution.

### ISSUE THREAD

**Issue by aswinramakrishnan** [codebasics/py#32]
Hello, 

Thanks for the lesson on linked list. I understood it completely.

This should work. Please update.

 
   def insertAtBegin(self, data):
        if self.head is None:
            node = Node(data, self.head, None)
            self.head = node
            return
        node = Node(data, self.head, None)
        node.next = self.head
        self.head.prev = node
        self.head = node

**Comment by dhavalsays** [comment]
This is fixed now
